#!/bin/bash
#PBS -P MSLC
#PBS -N mslc_finetunes
#PBS -J 0-153
#PBS -q midgpu
#PBS -j oe
#PBS -o ./logs/pbs/finetune/^array_index^/
#PBS -l ncpus=4
#PBS -l ngpus=1
#PBS -l mem=8GB
#PBS -l walltime=240:00:00
#PBS -m abe
#PBS -M dh2306@msstate.edu
 
cd ${PBS_O_WORKDIR}
module load cuda10.2/toolkit
module load python
conda init
source ~/.bashrc
conda activate mslc
python finetune.py --num_workers $PBS_TASKNUM
