#!/bin/bash
#PBS -N r2665-hrnet-pretrain_hrnet_w48_ae
#PBS -q biggpu
#PBS -j oe
#PBS -o ./logs/pbs/r2665-hrnet-pretrain_hrnet_w48_ae.out
#PBS -l ncpus=2
#PBS -l ngpus=1
#PBS -l mem=32GB
#PBS -l walltime=240:00:00
#PBS -m abe
#PBS -M dh2306@msstate.edu
 
cd ${PBS_O_WORKDIR}
module load cuda10.2/toolkit
module load python
conda init
source ~/.bashrc
conda activate mslc
python pretrain.py --model hrnet_w48 --pretrain_scheme ae --pretrain_hdf5_path /scratch/r2665/mslc/pretrain.hdf5 --mini_batch_size 8 --num_workers 2 --learning_rate_factor 0.001
